module.exports = (erro, req, res, next) => {
  // logica para tratar o erro
  res.status(318).end()
};